config/routes.rb
Rails.application.routes.draw do

  root 'buildings#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :invitations => 'users/invitations'
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end



  resources :buildings

  resources :users, :only => [:index, :show]


  resources :buildings , only: [:create ,:new ] do
    resources :parts, only: [:new,:create,:edit,:update, :show,:destroy]
  end

  resources :buildings , only: [:create ,:new ] do
    resources :tops , only: [:index, :show] do
      resources :mainparts, only: [:index, :show] do
        resources :parts, only: [:new,:create,:edit,:update] 
      end
    end
  end



  resources :buildings ,only: [:show] do
    resources :reforms ,only: [:new, :create,:destroy, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
	belongs_to :user
	has_many :parts, foreign_key: :building_id, dependent: :destroy
	has_many :reforms, foreign_key: :building_id, dependent: :destroy
	#has_many :symptom, through: :parts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :building
end

app/models/detail.rb
class Detail < ApplicationRecord
	belongs_to :symptom
	#has_many :parts
end

app/models/mainpart.rb
class Mainpart < ApplicationRecord
	#belongs_to :part
	has_many :materials
	belongs_to :top
end

app/models/material.rb
class Material < ApplicationRecord
	belongs_to :top
	belongs_to :mainpart
	has_many :symptoms
end

app/models/part.rb
class Part < ApplicationRecord
	belongs_to :building
	belongs_to :detail
	#has_one :detail
	validates :detail_id, presence: true
end

app/models/reform.rb
class Reform < ApplicationRecord
	belongs_to :building
end

app/models/symptom.rb
class Symptom < ApplicationRecord
	belongs_to :top
	belongs_to :mainpart
	belongs_to :material
	has_many :details
end

app/models/top.rb
class Top < ApplicationRecord
	has_many :mainparts
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :buildings, foreign_key: :user_id, dependent: :destroy
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
#before_action :authenticate_user!
  def new
    @part = Part.new
  end

  def create
    @part = Part.new(part_params)
    @part.building_id = params[:building_id]
    @part.detail_id = params[:part][:detail_id]
    #binding.pry
    if @part.save
      redirect_to edit_building_part_path(:building_id => @part.building_id, :id=> @part.id)
    else
      redirect_to new_building_part_path
    end
  end

  def index
  end

  def show
    @part = Part.find(params[:id])
  end

  def edit
    @part = Part.find(params[:id])
    @part.cond ||= @part.detail.condition
    @part.treat ||= @part.detail.treatment
  end

  def update
    @part = Part.find(params[:id])
    @part.update_attributes(part_params)
    @part.part_type = @part.detail.detail_type
    if @part.save
      #redirect_to root_path
      redirect_to building_path(:id => @part.building_id)
    end
  end

  def destroy
    @part = Part.find(params[:id])
    @part.destroy
    redirect_to building_path(params[:building_id])

  end

  private
  # permit(:, keys: [:clubname, :clubtype, :text, :population, :profile_img , {:college_ids => []} ]) 
  def part_params
    params.require(:part).permit(:cond, :treat ,:detail_id,:building_id, :score, :part_type, :picturename)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  	@tops = Top.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/mainparts_helper.rb
module MainpartsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/reforms_helper.rb
module ReformsHelper
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/parts/create.html.erb
<h1>Parts#create</h1>
<p>Find me in app/views/parts/create.html.erb</p>

app/views/parts/edit.html.erb
<p id = "part_type"><%= @part.detail.detail_name %></p>
<div class="box30">
	<%= form_for @part, url: building_part_path do |f| %>
	    <div class="box-title"><p id="part_cond" > 現状 </p></div>
	    <%= f.text_area :cond , value: @part.cond %>
	    <div class="box-title"><p id="part_treat" > 処置 </p></div>
	    <%= f.text_area :treat, value: @part.treat  %>
	     <p id = "part_detail">対応する写真タイトル </p>
		<%= f.text_field :picturename %>
		<div class="row">
		    <div class="col-xs-12">
		    点数を選択してください
		    	
				<div class="select-wrap select-primary">
		  		<%= f.select :score, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7]] ,class:"form-control" %>
				</div>
			</div>
		</div>
		<div><%= f.submit "資料を作成", class: 'btn btn-primary btn-lg btn-block' %> 
		</div>
	<% end %>
</div>

app/views/parts/index.html.erb
<h1>Parts#index</h1>
<p>Find me in app/views/parts/index.html.erb</p>

app/views/parts/new.html.erb
<div class="topicpath">
    <ol>
    	<li><a href="/">ホーム</a></li>
        <li><a href="/buildings/<%= params[:building_id] %>"><%= Building.find(params[:building_id]).building_name %></a></li>
        <li><a href="/buildings/<%= params[:building_id] %>/tops"><%= Top.find(params[:top_id]).maintitle %>（ <%= Mainpart.find(params[:mainpart_id]).mp_name %> ）</a></li>
    </ol>
</div>



<div>

	<%= form_for @part, url: building_parts_path(building_id: params[:building_id], detail_id: params[:detail_id]) do |f| %>
		<% Material.where(top_id: params[:top_id],mainpart_id: params[:mainpart_id]).each do |material|%>
			<div class="collection_radio_button">
				<div class="box-title"><%= material.mate_name %></div>
				<% material.symptoms.each do |symptom| %>
					<%= f.collection_radio_buttons(:detail_id, Detail.where(symptom_id: symptom.id ,material_id: material.id ,top_id: params[:top_id], mainpart_id: params[:mainpart_id]), :id, :detail_name , include_hidden: false) do |b| %>
						<div class="box-contents">
							<h3><%= b.label { b.radio_button + b.label } %></h3>
							<h style="color:red;">[現状]</h>
							<%= b.object.condition %>
							<h style="color:blue;"> [診断] </h>
							<%= b.object.treatment %>
						</div>
					<% end %>
				<% end %>
			</div>
		<% end %>
		<%= f.submit '次へ進む', class: 'btn btn-primary btn-lg btn-block' %>
	<% end %>
</div>

app/views/parts/show.html.erb
<div class="mainbox"> <%= @part.building.building_name %> > <%=Detail.find(@part.detail.id).detail_name%></div>


 <div class="col-md-12">
        <table class="table">

            <tbody>
                <tr>
                    <th class="table-danger" style="font-size: 1.5em; text-align: center;">現状</th>
                    <td><%= @part.cond %></td>
                    <% if @part.building.user.id == current_user.id %>
                    <td><%= link_to "編集",edit_building_part_path ,method: :get ,class: 'btn btn-success'%></td>
                    <% end %>
                </tr>
                <tr>
                    <th class="table-primary" style="font-size: 1.5em; text-align: center;">処置</th>
                    <td><%= @part.treat %></td>
                    <% if @part.building.user.id == current_user.id %>
                    <td><%= link_to "編集",edit_building_part_path ,method: :get ,class: 'btn btn-success'%></td>
                    <% end %>
                </tr>
                <tr>
                    <th class="table-muted" style="font-size: 1.5em; text-align: center;">点数</th>
                    <td ><%= @part.score %>点</td>
                    <% if @part.building.user.id == current_user.id %>
                    <td><%= link_to "編集",edit_building_part_path ,method: :get ,class: 'btn btn-success'%></td>
                    <% end %>
                </tr>
                <tr>
                    <th class="table-success" style="font-size: 1.5em; text-align: center;">写真ファイル名</th>
                    <td><% if @part.picturename.blank? %>不明
                        <% else %>写真タイトル<%= @part.picturename %>
                        <% end %>
                    </td>
                    <% if @part.building.user.id == current_user.id %>
                    <td><%= link_to "編集",edit_building_part_path ,method: :get ,class: 'btn btn-success'%></td>
                    <% end %>
                </tr>
            </tbody>
        </table>

<% if @part.building.user.id == current_user.id %>
 <div><%= link_to "削除",building_part_path ,method: :delete ,class: "btn btn-danger btn-block"%></div>
<% end %>

app/views/tops/index.html.erb
<div>
  <% @tops.each do |top| %>
    <div class="collection_radio_button">
        <div class="box-top-title"><%= top.maintitle  %></div>
        <% top.mainparts.each do |mainpart| %>
        <div class="box-select-mainpart"><%= link_to mainpart.mp_name ,new_building_top_mainpart_part_path(building_id: params[:building_id],top_id: top.id, mainpart_id: mainpart.id) %>
        </div> 
        <% end %>
    </div>
  <% end %>
</div>

 

app/views/tops/show.html.erb
<h1>Tops#show</h1>
<p>Find me in app/views/tops/show.html.erb</p>