config/routes.rb
Rails.application.routes.draw do

  root 'buildings#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :invitations => 'users/invitations'
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end



  resources :buildings

  resources :users, :only => [:index, :show]


  resources :buildings , only: [:create ,:new ] do
    resources :parts, only: [:new,:create,:edit,:update, :show,:destroy]
  end

  resources :buildings , only: [:create ,:new ] do
    resources :tops , only: [:index, :show] do
      resources :mainparts, only: [:index, :show] do
        resources :parts, only: [:new,:create,:edit,:update] 
      end
    end
  end



  resources :buildings ,only: [:show] do
    resources :reforms ,only: [:new, :create,:destroy, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
	belongs_to :user
	has_many :parts, foreign_key: :building_id, dependent: :destroy
	has_many :reforms, foreign_key: :building_id, dependent: :destroy
	#has_many :symptom, through: :parts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :building
end

app/models/detail.rb
class Detail < ApplicationRecord
	belongs_to :symptom
	#has_many :parts
end

app/models/mainpart.rb
class Mainpart < ApplicationRecord
	#belongs_to :part
	has_many :materials
	belongs_to :top
end

app/models/material.rb
class Material < ApplicationRecord
	belongs_to :top
	belongs_to :mainpart
	has_many :symptoms
end

app/models/part.rb
class Part < ApplicationRecord
	belongs_to :building
	belongs_to :detail
	#has_one :detail
	validates :detail_id, presence: true
end

app/models/reform.rb
class Reform < ApplicationRecord
	belongs_to :building
end

app/models/symptom.rb
class Symptom < ApplicationRecord
	belongs_to :top
	belongs_to :mainpart
	belongs_to :material
	has_many :details
end

app/models/top.rb
class Top < ApplicationRecord
	has_many :mainparts
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :buildings, foreign_key: :user_id, dependent: :destroy
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
  	@buildings = Building.all.order("id DESC")
  end

  def new
  	@building = Building.new
  end

  def create
    @building = Building.new(building_params)
    @building.user_id = user_id
    if @building.save
      redirect_to building_path(@building.id)
    else
      redirect_to new_building_path
    end
  end

  def show
  @building = Building.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf do
          report = BuildingPDF.create @building
          send_data report.generate,
                    filename:    "#{@building.id}.pdf",
                    type:        "application/pdf",
                    disposition: "inline"
        end
      end
  end

  def edit
    @building = Building.find(params[:id])
  end

  def update
    @building = Building.find(params[:id])
    @building.update_attributes(building_params)
    if @building.save
      #redirect_to root_path
      redirect_to building_path(id: @building.id)
    end

  end
  


  private
    def building_params
      params
      .require(:building)
      .permit(:building_name, :building_place, :building_year, :building_scale, :building_type ,:building_construction)
    end
    def user_id
    	current_user.id
    end
end 

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  	@tops = Top.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/mainparts_helper.rb
module MainpartsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/reforms_helper.rb
module ReformsHelper
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buildings/edit.html.erb
<%= form_for  @building, url: building_path  do |f| %>

<table class="type10">
    <tbody>
	<tr>
        <th style="font-size: 25px"><%= f.label :物件名称 %></th>
        <td><%= f.text_field :building_name, placeholder: "   物件名称", :size => "80%" %></td>
    </tr>
    <tr>
        <th style="font-size: 25px"><%= f.label :所在地 %></th> 
        <td><%= f.text_field :building_place, placeholder: "   所在地", :size => "80%" %></td>
    </tr>
    <tr>
        <th style="font-size: 25px"><%= f.label :築年数 %></th>
        <td><%= f.text_field :building_year, placeholder: "   建物の年齢", :size => "30*60" %></td>
    </tr>
    <tr>
    	<th style="font-size: 25px"><%=  f.label :物件規模 %></th>
        <td><%= f.text_field :building_scale, placeholder: "   建物の大きさ", :size => "30*60" %></td>
    </tr>
    <tr>
        <th style="font-size: 25px"><%= f.label :物件種別 %></th>
        <td><%= f.text_field :building_construction, placeholder: "   建物の種類", :size => "40%" %></td>
    </tr>
    </tbody>
</table>

<%=f.submit '次 へ', class: 'btn btn-primary btn-lg' %>

<%end%>

app/views/buildings/index.html.erb
<div class="mainbox">
資料一覧
</div>
<div class="container">
<!-- <div class="col-md-12"> -->
	
	<% @buildings.each do |b| %>   
	<div class="col-md-3">
		<%= link_to  building_path(b.id) do %>  

			<div id="building">
				<div class="building_box box_detail">
					<div class="building_name"><%= b.building_name %>
					</div>
					<div class="user_name">
						<div><%= b.user.name %>さん</div>
					</div>
				</div>  
			</div>
		<% end %>
	</div>
	<% end %>
	
<!-- </div> -->
</div>

<% if user_signed_in? %>
	<%= current_user.name %>さん ログイン
	<%= link_to "投稿", new_building_path, class: 'btn btn-primary' %>
	<%= link_to "ログアウト", destroy_user_session_path, class: 'btn btn-primary',method: :delete%>
	<%= link_to "招待", new_user_invitation_path, class: 'btn btn-primary',method: :get %>

<% else %>
	<%= link_to "ログインする", new_user_session_path, class: 'btn btn-primary', method: :post %>
	<%= link_to "新規登録する", new_user_registration_path, class: 'btn btn-primary', method: :get  %>
<% end %>


<div class="btn_new_b">
 <%= link_to "+", new_building_path %>
</div>
</div>

app/views/buildings/new.html.erb
<%= form_for @building do |f| %>


<div class="container">
<div class="col-md-12">
<div><%= f.label :物件名 %></div>
<%= f.text_field :building_name, placeholder: "  例）サンヴァリエ日吉 4号棟", :size => "80%" %>

<div><%= f.label :所在地 %> </div>
<%= f.text_field :building_place, placeholder: "  例） 神奈川県横浜市港北区下田町４丁目" , :size => "80%" %>

<div><%= f.label :築年数 %></div>
<%= f.text_field :building_year, placeholder: "  例） 16年" %>

<div><%=  f.label :規模 %></div>
<%= f.text_field :building_scale, placeholder: "  例） 1棟 10階建て", :size => "30*60" %>

<div><%= f.label :物件種別 %></div>
<%= f.text_field :building_construction, placeholder: "  例） マンション", :size => "40%" %>
</div>

<%=f.submit '次 へ', class: 'btn btn-primary btn-lg btn-block' %>

<%end%>
</div>

app/views/buildings/show.html.erb
<div class="mainbox" style="background-color: #1E90FF;">♦︎<%= @building.building_name %>♦︎</div>
<div style="margin: 10px;">
	<div class="container">
	    <div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-striped table-bordered">
					<thead>
					    <tr>
					        <th>部位</th>
					        <th>素材</th>
					        <th>仕上げ材</th>
					    </tr>
					</thead>
					<% @building.reforms.each do |r|%>
						<tbody>
						    <tr>
						        <td class="col-xs-2"><%= r.reform_part %></td>
						        <td class="col-xs-2"><%= r.reform_material %></td>
						        <td class="col-xs-2"><%= r.reform_working_out %></td>

						        <% if r.building.user.id == current_user.id %>

						         <td class="col-xs-1"><%= link_to "削除", building_reform_path(building_id: @building.id, id: r.id), method: :delete ,class: "btn btn-danger" %></td>
		
						         <td class="col-xs-1"><%= link_to "編集", edit_building_reform_path(building_id: @building.id, id: r.id),method: :get ,class: "btn btn-success"%></td>
								<% end %>
						    </tr>
						</tbody>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

<% if @building.user_id == current_user.id %>
	<%= link_to '♦︎各部位の素材/仕上げ素材♦︎を追加' ,new_building_reform_path(building_id: params[:id]), class: 'btn btn-primary btn-lg ' %>
	<%= link_to '建物詳細を編集', edit_building_path(@building.id), class: 'btn btn-success btn-lg ' %>
<% end %>


<div class="mainbox" style="background-color: #1E90FF;">♦︎内容♦︎</div>

<div class="container">
<% if @building.parts.present? %>

	    <div class="col-xs-12">
				<div class="table-responsive">
					<table class="table table-striped table-bordered">

					    <thead>
					        <tr>
					        	<th>資料</th>
					            <th>現状</th>
					            <th>処置</th>
					            <th>点数</th>
					            <th>写真ファイル名</th>
					        </tr>
					    </thead>
					    <% @building.parts.each do |p| %>
						    <tbody>
						        <tr>

						            <td class="col-xs-2"><%= link_to "#{p.detail.detail_name}・#{p.part_type}", building_part_path(building_id: params[:id],id: p.id) , class: 'btn btn-info btn-lg' %></td>					
						            <td class="col-xs-3"><%= truncate(p.cond, length:40,omission: "...") %></td>
						            <td class="col-xs-3"><%= truncate(p.treat, length:40,omission: "...") %></td>
		
						            <td class="col-xs-1" style="text-align: center"><%= p.score %></td>

									<td class="col-xs-2"><%= p.picturename %></td>

						
						        </tr>
						    </tbody>
					    <% end %>
					</table>
				</div>
		</div>

<% end %>
</div>



<div>
<%= link_to '新規作成', building_tops_path(building_id:  params[:id]), class: 'btn btn-primary btn-lg btn-block' %>
</div>
<div>
	<% if !@building.parts.blank? %>
		<%= link_to "PDFで表示",building_path(@building, format: "pdf",:target=>["_blank"]), class: 'btn btn-success btn-lg' %>
	<%end%>
	<%= link_to '戻る',root_path, class: 'btn btn-default btn-lg' %>
</div>
</div>